# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190307_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=32, verbose_name='账户'),
        ),
    ]
